-- SELECT 
-- A.TITLE,
-- A.BOARD_ID,
-- B.REPLY_ID,
-- B.WRITER_ID, 
-- B.CONTENTS, 
-- B.CREATED_DATE
-- FROM USED_GOODS_BOARD AS A
-- JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
-- WHERE 
-- DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
-- ORDER BY B.CREATED_DATE, A.TITLE;


SELECT 
  A.TITLE,
  A.BOARD_ID,
  B.REPLY_ID,
  B.WRITER_ID, 
  B.CONTENTS,
  DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B ON B.BOARD_ID = A.BOARD_ID
WHERE YEAR(A.CREATED_DATE) = '2022' AND MONTH(A.CREATED_DATE) = '10'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;

